"""§86 — Static per-tau ``fmax`` calibration tables.

The §82 sharing-operability classifier and the §84 max-margin ``fmax``
rule both need a per-tau ``fragmentation_max`` operating point. §82
ships an inline midpoint formula (`(f0 + f10) / 2`) that depends only
on the row passed to ``classify_curve``. §84 strictly improves the
midpoint by maximising the f0/f10 separability margin over a paired
bootstrap distribution — but that requires the bootstrap distribution
to be in hand at decision time, which the runtime classifier does
*not* have.

Rather than recompute the bootstrap on every consolidate() (expensive,
non-deterministic, requires the LoCoMo-style corpus), we ship a small
static lookup of pre-computed max-margin ``fmax`` values per tau. The
numbers are read from ``bench/results/fmax_max_margin.json`` and
``bench/results/synthetic_fmax_max_margin.json`` which are produced by
``evals.fmax_max_margin``. The values are checked into source as a
plain dict so consolidation has no I/O dependency.

This is the runtime arm of pickup #3 from NEXT.md: makes max-margin a
*runtime* knob (`recommended_fmax(..., max_margin=True)`), not just a
paper figure.

Why two corpora
---------------
``LOCOMO`` is the realistic-noise meter: f0 is non-zero, the f0/f10
clouds overlap, max-margin is measurably better than midpoint at the
borderline tau bins (§84 lift up to +0.0093 at tau=0.15).

``SYNTHETIC`` is the calibration meter: f0 == 0 by construction
(§85 disjoint-core recipe), so midpoint and max-margin agree at
margin=1.0 (lift=0). The synthetic table is shipped for completeness
and as a regression check — if a future change shifts synthetic
numbers, the calibration table will fail validation in tests.

Selection
---------
The default is ``LOCOMO``: real-corpus calibration. ``select_table``
exists for tests and for future paper-figure work that wants to
toggle calibration regimes.
"""

from __future__ import annotations

from typing import Mapping

# Source: bench/results/fmax_max_margin.json (run 2026-05-22).
# Generated by ``python -m evals.fmax_max_margin --in
# bench/results/locomo_fragmentation_per_tau_bootstrap.json``.
# n_boot=100, n_schemas=543. Keys are tau (rounded to 4 decimals).
LOCOMO_FMAX_MAX_MARGIN: dict[float, float] = {
    0.10: 0.1486,
    0.15: 0.6740,
    0.20: 0.9021,
}

# Source: bench/results/synthetic_fmax_max_margin.json (run 2026-05-22).
# Synthetic disjoint-core recipe; f0_mean is identically 0 across
# all bootstrap reps so margin=1.0 and the midpoint/max-margin lift
# is 0.0 by construction.
SYNTHETIC_FMAX_MAX_MARGIN: dict[float, float] = {
    0.10: 0.0381,
    0.15: 0.0381,
    0.20: 0.0369,
    0.25: 0.0381,
    0.30: 0.0387,
}

# Tolerance for tau-key matching: bootstrap drivers parameterize tau
# in 0.05-step grids; users may pass anything ratio-y. We accept any
# tau within `_TAU_TOL` of a calibrated key.
_TAU_TOL = 1e-3


def _lookup(table: Mapping[float, float], tau: float) -> float | None:
    """Return the calibrated fmax for ``tau`` if any key is within
    ``_TAU_TOL``, else None. Pure, deterministic, O(n_keys)."""
    if tau is None:
        return None
    best: float | None = None
    best_d = _TAU_TOL
    for k, v in table.items():
        d = abs(k - tau)
        if d <= best_d:
            best = v
            best_d = d
    return best


def select_table(name: str = "LOCOMO") -> Mapping[float, float]:
    """Return the named calibration table (case-insensitive).

    Currently supported: ``"LOCOMO"`` (default), ``"SYNTHETIC"``.
    Raises ``KeyError`` for unknown names — callers should not
    silently fall back."""
    key = (name or "").strip().upper()
    if key in ("", "LOCOMO"):
        return LOCOMO_FMAX_MAX_MARGIN
    if key == "SYNTHETIC":
        return SYNTHETIC_FMAX_MAX_MARGIN
    raise KeyError(f"unknown calibration table: {name!r}")


def lookup_max_margin_fmax(
    tau: float,
    *,
    table: str | Mapping[float, float] = "LOCOMO",
) -> float | None:
    """Return the §84 max-margin fmax for ``tau`` from a static table.

    Returns None if ``tau`` is not within ``_TAU_TOL`` of any
    calibrated key. Callers should fall back to the §82 midpoint
    formula on a None return — the contract is "use this if we have
    a number, otherwise compute online".
    """
    if tau is None:
        return None
    tab = select_table(table) if isinstance(table, str) else table
    return _lookup(tab, float(tau))


__all__ = [
    "LOCOMO_FMAX_MAX_MARGIN",
    "SYNTHETIC_FMAX_MAX_MARGIN",
    "select_table",
    "lookup_max_margin_fmax",
]
